name: 'Build library and run tests'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/wmww/gtk4-layer-shell-ci:latest
    steps:
    - uses: actions/checkout@v4
    - name: Meson
      run: meson setup -Dexamples=true -Ddocs=true -Dtests=true -Db_sanitize=address,undefined build
      env:
        CFLAGS: -Werror
    - name: Build
      run: ninja -C build
    - name: Test
      run: ASAN_OPTIONS="detect_leaks=0" LD_PRELOAD="$(gcc -print-file-name=libasan.so)" meson test -C build --verbose
