name: 'Build library and run tests'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Apt update
      run: sudo apt update
    - name: Install depends
      run: sudo apt install meson libwayland-dev wayland-protocols libgtk-4-dev gobject-introspection libgirepository1.0-dev valac gtk-doc-tools
    - name: Meson
      run: meson setup -Dexamples=true -Ddocs=true -Dtests=true build
      env:
        CFLAGS: -Werror
    - name: Build
      run: ninja -C build
    - name: Test
      run: meson test -C build --verbose
